### ISSUE TITLE
Adopting this crate

### ISSUE THREAD

**Issue by btwiuse** [taquarius/slap#1]
Hi, I'm interested in taking ownership of this crate if it's available. I'd like to use the name for a simplified version of `clap`. `slap` would be a perfect name for that idea, because the difference between slap and clap is that the former is done with one hand and the latter is done with two hands. My username on crates.io is `btwiuse`. Thanks in advance!

**Comment by taquarius** [comment]
I just added you as an owner. Once you have accepted it, feel free to remove me as an owner on the crate.
